import * as React from 'react';
import { UploadComponent } from "../../../components";

export type batchClaimDocUploaderProps = PopupContentProps & {
    dataId: string;
    fileUploaded: { (): void };
    onClosePopup: { (): void };
    saveUrl: string;
};

export class BatchClaimDocUploader extends React.Component<batchClaimDocUploaderProps, {}> {
    private onUploadComplete = (res: boolean) => {
        res && this.props.fileUploaded();
    }

    private closePopup = () => {
        this.props.onClosePopup();
    }

    render() {
        return (
            <div className="popup-container" data-qa="BatchClaimDocumentUploadPopUpContainer">
                <span data-qa="ImportantNotice">As set forth in the important notice for this event:</span>
                <ul style={{ paddingLeft: '15px' }}>
                    <li data-qa="AllNecessaryDocumentsFullyPrepared">Please include all necessary documents fully prepared for submission in the local
                         market, including documents not generated by the ADROIT&trade; system.</li>
                    <li data-qa="AllPhysicalDocuments">Please ensure that all required physical documentation is submitted to Goal.</li>
                </ul>
                <UploadComponent
                    onComplete={this.onUploadComplete}
                    saveData={{ claimId: this.props.dataId.toString() }}
                    saveUrl={this.props.saveUrl}
                    qa="BatchClaimDocumentUpload"
                    allowedExtensions={[".bmp", ".jpg", ".jpeg", ".png", ".csv", ".pdf", ".rar", ".zip", ".xls", ".xlsx", ".xml", ".doc", ".docx"]}
                    onCancelAndClose={this.closePopup}
                   >
                </UploadComponent>
            </div>
        );
    }
}